### ISSUE TITLE
[Lexer] Do not emit errors as tokens

### ISSUE THREAD

**Issue by simonlindholm** [HalfVoxel/koolc#3]
If we instead give the lexer some sort of "emit error" function it can call, we can:
- avoid BAD tokens, which have no meaning to the parser
- emit errors like "too large number" while still saying to the parser that the thing we lexed was an integer.
- be more sure that lexer errors don't get silently ignored.

**Comment by HalfVoxel** [comment]
But the lexer is a implemented as a stream of tokens, this would break that abstraction a lot.

Ideally I don't think the lexer should parse integers as 32-bit integers, instead it should be able to store arbitrary sized integers, the type resolver would have to check if a particular integer was valid in the context it is used. E.g

    int32 a = 100000000000; // Invalid
    int64 a = 100000000000; // Valid

And we would be able to do it like Go does it: constants are arbitrary precision and are evaluated during compile time. So e.g

    int32 c = (100000000000 >> 32); // Still compiles

Not really suggesting we go that route, but I think it is a cleaner approach to let the type resolver handle the integer sizes.

**Comment by HalfVoxel** [comment]
For the errors we could possibly add another stage in the pipeline which simply takes the stream of tokens from the lexer and lets all non-error tokens pass through, but logs all error tokens.
It would essentially be the same as adding an emitError method on the lexer, but it doesn't break the iterator abstraction.

**Comment by simonlindholm** [comment]
> But the lexer is a implemented as a stream of tokens, this would break that abstraction a lot.

Yes, indeed the lexer would no longer just be a vanilla side-effect-free iterator of tokens. But adding an error reporter to the stream interface seems generally useful also for e.g. parsing. Adding another phase would also work, but I don't really see the advantage - wouldn't that phase break the abstraction about equally much?

> Ideally I don't think the lexer should parse integers as 32-bit integers, instead it should be able to store arbitrary sized integers, the type resolver would have to check if a particular integer was valid in the context it is used.

Sure. But say we encounter "123abc" or an unterminated string literal - in these cases we may also want to emit an error and some half-lie as a token.

**Comment by HalfVoxel** [comment]
> Adding another phase would also work, but I don't really see the advantage - wouldn't that phase break the abstraction about equally much?
True.

> Sure. But say we encounter "123abc" or an unterminated string literal - in these cases we may also want to emit an error and some half-lie as a token.
Indeed, I was not arguing against having some kind of mechanism for reporting errors, I was merely objecting against the special case of only allowing 32 bit integers as integer literals, since if we allow integers of any size we would not have the problem of the parser not getting information about that it was an integer we parsed:
> emit errors like "too large number" *while still saying to the parser that the thing we lexed was an integer*.
