### ISSUE TITLE
[Lexer] Better error handling for lone | and &

### ISSUE THREAD

**Issue by HalfVoxel** [HalfVoxel/koolc#6]
Currently it prints "invalid character" and emits a BAD token, however it would be better to print "found lone '|'" and emit an OR token (or AND token for '&').

**Comment by simonlindholm** [comment]
Seems pretty unnecessary to me (I think `invalid character "|"` or `unrecognized operator "|"` would be clear enough), but perhaps we could improve things more generally by emitting a sort of "unknown operator token" (without semantics) for unrecognized characters.

**Comment by HalfVoxel** [comment]
But how would we be able to classify it as an operator? It could be anything really?
Or do you propose that we explicitly flag '|' and '&' as unknown operators?

**Comment by simonlindholm** [comment]
I guess most non-alphanumeric characters that aren't `"'()[]{};:` could be seen as operators. But sure, explicitly saying that to the user might seem weird, even though it would probably work for the purpose of parsing. I still think `invalid character "|"`` is not bad.

Looking at what other compilers do for unrecognized characters:
- gcc says `stray "c" in program`
- rustc says `unknown start of token: c`
- clang says things like `expected expression`, so it probably silently tokenizes arbitrarily?

but then, they also handle all reasonable characters... Rustc then terminates if it fails to lex; the others fail with a "required semicolon" or so when parsing.

**Comment by HalfVoxel** [comment]
Ok, fair enough. We can leave it as it is then.
