### ISSUE TITLE
Support --tokens flag

### ISSUE THREAD

**Issue by simonlindholm** [HalfVoxel/koolc#7]

**Comment by simonlindholm** [comment]
Maybe have it enter a compatibility mode where escape sequences are not parsed...

**Comment by HalfVoxel** [comment]
I don't think escape sequences should interfere. Hopefully his tests are not that evil.

**Comment by simonlindholm** [comment]
Ok, hopefully. We should double-check against the provided reference compiler, anyway.

**Comment by HalfVoxel** [comment]
Should we include the reference output in the repo?

**Comment by simonlindholm** [comment]
Sounds reasonable, especially if we can add a script which does automated diffing.

**Comment by HalfVoxel** [comment]
I made a script for that, but I haven't committed it yet. Maybe we should include the reference compiler instead, then the script could just recalculate the reference output every time.

**Comment by simonlindholm** [comment]
Eh, it sounds ... morally wrong ... to include a formal dependency on an unknown third-party binary, and also would limit us if/when we want to add new language extensions. I like including reference output more.

**Comment by HalfVoxel** [comment]
Fair enough.
I will push the reference output for all our tests as well as a testing script.
